server:
  port: 8887

github:
  client:
    id: 1
    secret: 1
  redirect:
    uri: http://localhost:8887/callback


spring:
  datasource:
    url: jdbc:h2:~/community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true