server:
  port: 8887

github:
  client:
    id: a30fee9101e3e694b1f2
    secret: 4fc50afb8b7290969c23d9939f563596bb724e7d
  redirect:
    uri: http://localhost:8887/callback


spring:
  datasource:
    url: jdbc:h2:~/community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true